name: Build SDL Win32

on:
  workflow_dispatch:

jobs:
  build-sdl-win32:
    runs-on: ubuntu-22.04
    name: Build sdl_win32 (Ubuntu)
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update && sudo apt install -y xorg-dev libsdl2-dev gcc-mingw-w64 libarchive-tools

      - name: Build SDL2.dll
        run: |
          make SDL2.dll

      - name: Build sdl_win32
        run: |
          make -j$(nproc) sdl_win32

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sdl_win32-build
          path: |
            sa2.sdl_win32.exe
            SDL2.dll

